childPipelines:
  scmUrls:
    - git@github.com:wahapo/child.git

jobs:
  main:
    requires: [ ~pr, ~commit ]
    image: node:8
    steps:
      - ls: ls
  main2:
    requires: [ ~main ]
    image: node:8
    steps:
      - ls: ls
  from-external-trigger:
    requires: [ ~sd@4:main-2 ]
    image: node:8
    steps:
      - ls: ls
