childPipelines:
  scmUrls:
    - git@github.com:wahapo/child.git

jobs:
  main:
    requires: [ ~pr, ~commit ]
    image: node:8
    steps:
      - ls: ls
  from-child-trigger:
    requires: [ ~sd@4:main ]
    image: node:8
    steps:
      - ls: ls
